kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: default
    image: node:lts-alpine
    commands:
      - npm install
      - npm run build
    when:
      branch:
        - master
      event:
        - push

  - name: publish
    pull: default
    image: plugins/npm
    environment:
      NPM_EMAIL:
        from_secret: npm_email
      NPM_PASSWORD:
        from_secret: npm_password
      NPM_REGISTRY:
        from_secret: npm_registry
      NPM_USERNAME:
        from_secret: npm_username
    when:
      branch:
        - master
      event:
        - push