pipeline:
  publish:
    image: node:lts-alpine
    secrets: [ npm_username, npm_password, npm_email, npm_registry ]
    commands:
      - npm install
      - npm run build
      - npm publish
    when:
      event: [ push ]
      branch: [ master ]
