pipeline:  
  build:
    image: node:lts-alpine
    commands:
      - npm install
      - npm run build
    when:
      event: [ push ]
      branch: [ master ]

  publish:
    image: plugins/npm
    secrets: [ npm_username, npm_password, npm_email, npm_registry ]
    when:
      event: [ push ]
      branch: [ master ]
