pipeline:  
  publish:
    image: node:lts-alpine
    secrets: [ nuget_user, nuget_password_base64 ]
    commands:
      - npm install
      - npm run build
      - npm publish
    when:
      event: [ push ]
      branch: [ master ]
